/**
 * Base URL from PokéAPI
 * @type {string}
 */
const base_url = "https://pokeapi.co/api/v2/";

/**
 * DIV where the Pokédex will be rendered
 * @type {HTMLDivElement}
 */
const pokedex = document.querySelector('.pokedex');

/** Class representing a Pokémon */
class Pokemon {
    /**
     * Create a Pokémon
     * @param    {int} number - The number that represents the Pokémon on the Pokédex
     * @param   {name} name - The name of the Pokémon
     * @param {string} sprite - The link to the Pokémon sprite
     * @param {Object} stats - All of the Pokémon stats
     */
    constructor(number, name, sprite, stats){
        this.number = number;
        this.name = name;
        this.sprite = sprite;
        this.stats = stats;
    }
}

/**
 * Capitalize the first letter of a word
 * @param   {string} word - The word to be capitalized
 * @returns {string} Word with the first letter capitalized
 */
function capitalize(word) {
    return word.charAt(0).toUpperCase() + word.slice(1);
}

/**
 * Compares two Pokémon based on their number attribute
 * @param {Pokemon} a - First Pokémon
 * @param {Pokemon} b - Second Pokémon
 * @returns {int}
 */
const compare = (a, b) => {
    if(a.number < b.number) return -1;
    if(a.number > b.number) return  1;
    return 0;
}

/**
 * Get data from the PokeAPI API and fill the pokemon array with the results
 * @param {renderPokedex} _callback - Renders Pokémon cards from the Pokémon array generated
 */
const getPokemons = async (_callback) => {
    /**
     * Array of the promises generated by the PokéAPI fetch operation
     * @type {Promise[]}
     */
    let promises = [];

    /**
     * Array of Pokémons
     * @type {Pokemon[]}
     */
    let pokemons = [];

    for(let index = 1; index <= 151; index++)
    {
        promises.push(fetch(`${base_url}pokemon/${index}`));
    };

    Promise.all(promises)
        .then(results => Promise.all(results.map(r => r.json())))
        .then(results => {
            results.map(pokemon => {
                let number  = pokemon.id;
                let name    = capitalize(pokemon.name);
                let sprite  = pokemon.sprites.front_default;
                let stats   = {
                    'HP':  pokemon.stats[0].base_stat,
                    'ATK': pokemon.stats[1].base_stat,
                    'DEF': pokemon.stats[2].base_stat,
                    'SPA': pokemon.stats[3].base_stat,
                    'SPD': pokemon.stats[4].base_stat,
                    'SPE': pokemon.stats[5].base_stat
                };

                pokemons.push(new Pokemon(number, name, sprite, stats));
            });

            renderPokedex(pokemons);
        });
};

/**
 * Render the Pokémon cards on the document from the Pokémon array
 * @callback renderPokedex
 * @param {Pokemon[]} pokemons - Array of Pokemon
 */
const renderPokedex = (pokemons) => {
    console.log(pokemons);

    for(let i = 0; i < 9; i++)
    {
        let pokemon = pokemons[i];
        console.log(pokemon);

        pokedex.innerHTML += `
            <div class="pokemon-card">
                <img src="${pokemon.sprite}" alt="${pokemon.name}" />
                <p>${pokemon.name}</p>
            </div>
        `;
    }
}

getPokemons(renderPokedex);